Web/Models/ErrorViewModel.cs
namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/ViewModels/Home/HomeIndexViewModel.cs
namespace Web.ViewModels.Home
{
    using System.Collections.Generic;
    using Domain.Models;

    public class HomeIndexViewModel
    {
        public List<Status> Statuses { get; set; }
    }
}

Web/ViewModels/Status/CreateStatusViewModel.cs
namespace Web.ViewModels.Status
{
    public class CreateStatusViewModel
    {
        public string Status { get; set; }
    }
}

Web/Controllers/HomeController.cs
namespace Web.Controllers
{
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading.Tasks;
    using Application.Services;
    using Domain.Models;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Microsoft.AspNetCore.Authorization;
    using ViewModels.Home;

    public class HomeController : Controller
    {
        private readonly IStatusService _statusService;

        public HomeController(IStatusService statusService)
        {
            _statusService = statusService;
        }
        
        public async Task<IActionResult> Index()
        {
            List<Status> statuses = await _statusService.GetAllChronological();
            HomeIndexViewModel viewModel = new HomeIndexViewModel{Statuses = statuses};
            
            return View(viewModel);
        }
    
        [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/StatusController.cs
namespace Web.Controllers
{
    using System.Threading.Tasks;
    using Application.Services;
    using Domain.Auth;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using ViewModels.Status;

    public class StatusController : Controller
    {
        private readonly IStatusService _statusService;
        private readonly UserManager<AppUser> _userManager;

        public StatusController(
            IStatusService statusService,
            UserManager<AppUser> userManager)
        {
            _statusService = statusService;
            _userManager = userManager;
        }
        
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddStatus([FromForm]CreateStatusViewModel viewModel)
        {
            AppUser currentUser = await _userManager.GetUserAsync(User);

            await _statusService.CreateStatus(viewModel.Status, currentUser);

            return RedirectToAction("Index");
        }
    }
}

Web/Views/Home/Index.cshtml
@model Web.ViewModels.Home.HomeIndexViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
    @foreach (var status in Model.Statuses)
    {
        <div class="card text-left">
            <div class="card-header">
                @status.Author.UserName <span class="float-right">@status.Date</span>
            </div>
            <div class="card-body">
                <p class="card-text">@status.Content</p>
                <button class="btn btn-outline-info" type="button" data-toggle="collapse" data-target="@($"#comments{status.Id.ToString().Replace("-","")}")" aria-expanded="false" aria-controls="@($"comments{status.Id.ToString().Replace("-","")}")">
                    Comments
                </button>
            </div>
            <div class="card card-body collapse" style="padding: 0" id="@($"comments{status.Id.ToString().Replace("-","")}")">
                <p style="margin: 1em">Comments</p>
            </div>
        </div>
    }
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Status" asp-action="Index">Create Status</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial"></partial>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Views/Status/Index.cshtml
@model Web.ViewModels.Status.CreateStatusViewModel
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Create post</h2>

<form asp-controller="Status" asp-action="AddStatus" method="post">
    <textarea asp-for="Status"></textarea>
    <input type="submit"/>
</form>